### ISSUE TITLE
Implementing audio playback natively

### ISSUE THREAD

**Issue by ZarTaen** [Archaegeo/DualUniverseLuaIssues#11]
While it may seem counter-intuitive from the creator to suggest such, I would like to see a native implementation for audio access in some way. I know of the abuse potential, but with the existing third-party implementations, the abuse potential is orders of magnitude higher. 

This could be handled similar to the current picture file CDN.  Additionally, it requires an RDMS right that allows or disallows access to "player resources", which in this case would be audioplayback altogether. 

I know that Copyright might become problematic with this. However, an alternative is exactly how audio_framework does it: allowing access to already existing files, ideally in a predefined Dual Universe folder, that the player specifically would have to put there, similar to how 3d models are handled with the scaffolding projector. That way, NQ does not become liable for any of the audio file distribution, but loses some of the control as well.

**Comment by NQ-Deckard** [comment]
Mechanics similar to the scaffolding projector might be viable, I'll feed this back to the team. Much of this however not as trivial due to legal strings.

**Comment by Dimencia** [comment]
To be fair, there is as much chance someone brings copyrighted lua into the game as bringing in copyrighted sounds

But if that's a concern, then consider: Lua API function to play a tone, of a specified frequency and duration (ideally in an async way that lets you play multiple at once).  And Lua API function to play a synthesized voice that pronounces some text, maybe Aphelia herself.  Both would only function from an explicitly-run control unit

No real chance of copyright problems, most things can still be done.  And much like the rest of the DU API, might provide a fun challenge as people work around the limitations and, for example, play midi files through tones

**Comment by samdeane** [comment]
Just a library of some predefined sounds we could play would be nice. Little pings, clicks, warning klaxons, people screaming "oh god, we're all going to die"*, etc.

(* ok, maybe I got carried away, but I'm sure many piloting scripts would find it useful)

**Comment by Archaegeo** [comment]
Closing as you can now play() sounds of your choosing.
