### ISSUE TITLE
Reverse RDMS rights for Lua scripts

### ISSUE THREAD

**Issue by ZarTaen** [Archaegeo/DualUniverseLuaIssues#12]
I think with the bad actor concerns around a lot of potential features and additions, there needs to be a crucial addition to the current RDMS: Rights for Lua scripts. 

This could range from something as simple as being allowed to use emitters/receivers to allowing audioplayback or input capture. While implementing this in a streamlined manner would be no easy task, I think it is a necessary step forward to give players more of a choice in what they accept, while it would allow a vast improvement in Lua capabilities to improve the overall game experience.

**Comment by NQ-Deckard** [comment]
Not likely to happen anytime soon, very significant change to the RDMS system.

**Comment by Archaegeo** [comment]
Closing for now
