### ISSUE TITLE
Adding additional script to DRM'ed control - programming board

### ISSUE THREAD

**Issue by Archaegeo** [Archaegeo/DualUniverseLuaIssues#13]
Ideal would be for DRM to only apply to scripts on the control unit / programming board when DRM is set, or different levels of DRM.

This would let you "buy" someone's chair with their script on it, but still add more scripting to it without loss of DRM but still having access to the existing script running (and with API/Hooks if made available).

EX:  Someone write a new engine script DLL. They DRM and sell it, and others can use calls to it for engine control without changing/taking the base code.   Or someone wants to add additional functionality to existing script on a control seat/pb.

**Comment by samdeane** [comment]
https://github.com/samedicorp/dualuniverse-feedback/issues/52

samedicorp/dualuniverse-feedback#52

**Comment by Archaegeo** [comment]
Closing as over 1 year old with no comment from NQ and similiar to other commented issue.
