### ISSUE TITLE
Elementification of Lua 

### ISSUE THREAD

**Issue by EasternGamer** [Archaegeo/DualUniverseLuaIssues#17]
## Intro
I struck a conversation with ZarTaen#6409 on how restrictive YOLOL code was in Starbase, how you had to have so many of this to do that, but, honestly, it's not a terrible idea. But instead of restricting what you can do currently, rather, it would be better to improve what you can do currently.

## Elementification
Essentially, Lua could be expanded to include more elements you link together. Like how you link a fuel tank to an engine to give it the fuel it needs to run, Lua should also link to elements to expand the functionality it could provide.
The current code limit of 200KB could be expanded through a "memory module" by another 100KB, up to two memory modules. Each module would be expensive to purchase, requiring tier three or four items to make.
Then you could add a CPU module to expand the execution limit or enable multi-threaded execution, up to 2.
Furthermore, you could add a graphics module to enable HUD screens.
Maybe even a dedicated display unit that displays how close you are in % of reaching the CPU limit.

Lastly, maybe it could tie into the energy/CPU system.

**Comment by NQ-Deckard** [comment]
Interesting idea, won't happen anytime soon. But will forward to the design team regardless.

**Comment by Archaegeo** [comment]
Closing as addressed by Deckard

**Comment by samdeane** [comment]
Similar ideas for reference: samedicorp/dualuniverse-feedback#29 and https://github.com/samedicorp/dualuniverse-feedback/issues/52
