### ISSUE TITLE
Databanks with many keys freeze the game

### ISSUE THREAD

**Issue by dlbd** [Archaegeo/DualUniverseLuaIssues#18]
Databank operations take a long time when the databank stores many keys. 

The following script freezes the game for almost 2 minutes:

```lua
databank.clear()

local t_start = system.getTime()

for i = 1, 3000 do
    databank.setIntValue(tostring(i), 0)
end

system.print(string.format("Total time: %.10f", system.getTime() - t_start))
```

Suggestions:
- optimize databank operations to take less time 
- limit the max number of keys in a databank to less than 500
- manually decrement the Lua instruction counter (`hookcount` of `lua_State`) in databank functions (to make the databank functions more "expesive" to call and have them trigger the CPU overload error)

**Comment by NQ-Deckard** [comment]
Bug recorded.

**Comment by Archaegeo** [comment]
Closing as collected
