### ISSUE TITLE
Need LUA access to camera location and orientation

### ISSUE THREAD

**Issue by Archaegeo** [Archaegeo/DualUniverseLuaIssues#2]
Need to be able to query via lua the in game camera location and its orientation.

**Comment by EasternGamer** [comment]
Also, optionally, if we can have head-bob is accounted for in the camera position, that would be excellent.

**Comment by EasternGamer** [comment]
Possible method calls:
`system.getCameraWorldPos()`
`system.getCameraRelativeOrientation()`

**Comment by NQ-Deckard** [comment]
Recorded feedback 👍
