### ISSUE TITLE
LUA screens do not support text rotation

### ISSUE THREAD

**Issue by nekranox** [Archaegeo/DualUniverseLuaIssues#24]
Currently it is not possible using the new LUA screen functions to rotate text. As a result, is it is **not possible to have a screen in portrait orientation with text**.

The only way to add text using the new functions is
`addText(layer, font, text, x, y)`
 
But the documentation states that this function does not support rotation
Screenshot: https://imgur.com/a/GHxK0w8
Documentation: https://board.dualthegame.com/index.php?/topic/22643-lua-screen-units-api-and-instructions-updated-19072021/

Text rotation is essential and should be high priority as many people use screens in portrait orientation and this will harm adoption of the new API

**Comment by samdeane** [comment]
A more general solution might be to allow layer rotation?

Then if you need to rotate some text (or anything else), you put it on a layer and rotate that.

**Comment by Archaegeo** [comment]
Closed as complete
