### ISSUE TITLE
Implement getProductInfo(productType)

### ISSUE THREAD

**Issue by samdeane** [Archaegeo/DualUniverseLuaIssues#29]
Analogous to `getSchematicInfo(schematicId)`, but returning information about a particular product, indexed by the type that `getSchematicInfo` supplies for products.

It would return a JSON record containing such useful things as:

- the full item name
- the item tier
- the item type
- the item mass
- the item volume
- the primary schematic ID for the product
- the ids of other schematics which produce the item as an additional product

**Comment by EasternGamer** [comment]
I would rather it return a Lua table than a JSON tbh.

**Comment by samdeane** [comment]
> I would rather it return a Lua table than a JSON tbh.

I completely agree, but I think that's a different request -- since I would want it to apply to _all_ APIs that currently return JSON.

The JSON thing feels to me like it's just the devs being a bit lazy and not bothering to do a proper mapping. It's easier to just get your C++ objects to output a string, and pass that across, so that's what they are doing. 

It's really not that difficult though to have a dictionary concept on the C++ side and have them output that, then bridge a dictionary across to Lua. Would be _way_ more sensible, and ought to be more efficient if done right.

**Comment by Archaegeo** [comment]
Closed as complete
