### ISSUE TITLE
Add INS (view) to actionOnStart/Stop/Loop

### ISSUE THREAD

**Issue by Archaegeo** [Archaegeo/DualUniverseLuaIssues#3]
Need INS added to keys seen by actionOnStart/Stop/Loop in order to tell when camera view changes.  Alternately a queryCameraView(). Or both.

**Comment by EasternGamer** [comment]
Alternative method call names:
`system.getCameraView()`
`system.getCameraViewType()`

**Comment by NQ-Deckard** [comment]
Recorded feedback 👍
