### ISSUE TITLE
Additional Import Libraries

### ISSUE THREAD

**Issue by EasternGamer** [Archaegeo/DualUniverseLuaIssues#31]
Some things are better imported into Lua rather than directly placed. An excellent example is the atlas. A highly detailed list of planets. If you added it directly in your script, you would use a significant amount of your script size budget for it.
Additionally, if anything changes, NQ can ensure that data is up to date.

So, as for the list, here it goes:
 - Atlas
 - Skill Data
 - Item Data
 - Schematic Data
 
 Skill data would link into item data so you can do your own calculations for skill bonuses. Additionally, optimally we would have an API along with it to get the effects of a skill.
 
 Schematic Data could be used to assist in creating a list of things to buy at the market automatically.
 Example Skill Data Format:
 ```lua
 {
    [sId] = { -- skill Id
        name = "Name",
        description = "Description",
        effect = effectId, -- If an effect is based off an ID, not sure the internals
        level = 1,
        multiplier = 0.05 -- Percentage amount per level
    }
 }
```

Example Schematic Data
```lua
{
    [sId] = { -- schematic Id
        name = "Name",
        description = "Description",
        item = itemId,
        tier = 1
    }
}
```

Example Item Data
```lua
{
    [sId] = { -- item Id
        name = "Name",
        description = "Description",
        schematic = schematicId,
        tier = 1,
        skills = {skillId1,skillId2,...}
    }
}
```

As for Atlas, something like the one found here: https://gitlab.com/JayleBreak/dualuniverse/-/blob/master/DUflightfiles/autoconf/custom/atlas_hyperion.lua

**Comment by EasternGamer** [comment]
Atlas and some more database/character info querying has been added! So mostly there.

**Comment by NQ-Ligo** [comment]
Hello !

To be honest, I wouldn't want to add more hardcoded files, like we did for the atlas if possible.
For the item, we already added an item API on 0.29 Athena update to get all the information about the items from their id like a Lua table.

We will try to continue in this direction for other things ;)
