### ISSUE TITLE
getKeys changed to getKeyList

### ISSUE THREAD

**Issue by MelaRisalo** [Archaegeo/DualUniverseLuaIssues#45]
this function is used on many scripts, to read keys from connected database (json.decode(getKeys()...

when i replaced this like it is intended these scripts wont work.
i am only the user of these scripts, so i do not know if its set up ok

i guess, getKeyList() is a new function introduced in Mercury Update? but the getKeys() is not deprecated, like other functions

**Comment by NQ-Ligo** [comment]
The databank.getKeys() functions is deprecated since Mercury API revamp.
When you call it it should display on your Lua chat (if executed explicitly) :
`Warning: method getKeys() is deprecated, use getKeyList() instead`
