### ISSUE TITLE
API access for wallet (check balance / make payments)

### ISSUE THREAD

**Issue by psyK2329** [Archaegeo/DualUniverseLuaIssues#5]
Feature request for API access to the wallet in order to check balance (maybe even list single transactions) and trigger payments.
Possible application would be e.g. automated casinos.

Triggered payments should ofc be safe and alway visible and confirmed by the user (through the regular confirmation interface)
View to the balance should possibly restricted if the construct is owned by the user.

**Comment by EasternGamer** [comment]
Also restrict it explicit programming board activation instead of via detection zones, etc.
You don't want those cages knowing your balance as well :)

**Comment by Archaegeo** [comment]
I think they have said they wont do wallet LUA, but Ill let Deckard weight in

**Comment by du-git** [comment]
> Also restrict it explicit programming board activation instead of via detection zones, etc.
> You don't want those cages knowing your balance as well :)

Limit to own constructs for balance should do the job. One might want a automated screen in his base that shows the latest transactions and chart e.g. from market sales or such.
Noboy else needs to know your transactions anyways.

@Archaegeo was that already confirmed from NQ?

**Comment by NQ-Deckard** [comment]
I don't expect that we will add a Wallet API anytime soon. If we do it would indeed be limited very harshly, and its extremely unlikely that we will allow for transactions to be triggered through Lua.

We may be able to do some form of short term log access to dispensers perhaps, allowing Lua to detect a dispenser transaction.

**Comment by ZarTaen** [comment]
In case of such a concern, as the transaction merely requires explicit consent, Id suggest a pay terminal element for that type of stuff, additionally to short term log access to dispensers.

**Comment by Archaegeo** [comment]
Closing as over 1 year old and Deckard indicated not likely.  Make a new one if desired.
