### ISSUE TITLE
Industry quantities are wrongs

### ISSUE THREAD

**Issue by Jericho1060** [Archaegeo/DualUniverseLuaIssues#6]
On industry data, depending on the mode (maintain, batch, ...) the setted amount returned in lua is not all the time the good value and it's most of the time a really big value.

**Comment by NQ-Deckard** [comment]
Would you be able to provide me with an example of this, and or reproduction including Lua code?
An XS construct with the required elements on that I can copy would suffice. :)

**Comment by Jericho1060** [comment]
> Would you be able to provide me with an example of this, and or reproduction including Lua code?
> An XS construct with the required elements on that I can copy would suffice. :)

Yes, i can easilly build something for you but it's a random bug, some values are corrects, some others are wrong, and i don't know why. This may need a larger amount of machines to see it.

Eventually, you can test stuff on my personnal industry i'm not really using it for now.

The script i'm using is a public script i'm sharing with everyone who wants it https://github.com/Jericho1060/DU-Industry-HUD

**Comment by Jericho1060** [comment]
Here a screen, as you can see, the 1st one is not good but the others look fine.
![image](https://user-images.githubusercontent.com/28439359/122084120-d04e1780-ce01-11eb-859a-061996d8a2ff.png)

**Comment by EasternGamer** [comment]
@Jericho1060, have you checked the PTS if maybe this has been fixed? They said in the patch notes a few bugs were fixed.

**Comment by Jericho1060** [comment]
> @Jericho1060, have you checked the PTS if maybe this has been fixed? They said in the patch notes a few bugs were fixed.

no, but i can test it, i'll have a look at it during the weekend but the pts data are old, my industry is pretty small on the pts, i'll check

**Comment by Jericho1060** [comment]
test it today, it seems to be solved, waiting for the version deployment on th elive server to confirm with a larger industry

**Comment by samdeane** [comment]
Something similar is still happening today on the live server. Possibly the fix hasn't made it across yet.

**Comment by NQ-Deckard** [comment]
Pretty sure I've got a good idea of what is causing this.
Checking with the team.

**Comment by Archaegeo** [comment]
Closed as complete, if still issue, reopen new issue

**Comment by ShadowLordAlpha** [comment]
For transfer units this bug appears to be back but some items appear to be set to zero and others to large values again

![image](https://user-images.githubusercontent.com/4204089/196029220-ba22d3b5-b31a-46f6-a070-0743eb347e2f.png)
![image](https://user-images.githubusercontent.com/4204089/196029230-bd70cfc3-729a-4311-a738-0f22590d69a9.png)
