### ISSUE TITLE
system.setScreen() is delayed

### ISSUE THREAD

**Issue by EasternGamer** [Archaegeo/DualUniverseLuaIssues#8]
Going frame by frame, I determined that system.setScreen(HTML) is delayed by exactly one frame. This becomes really problematic for an AR interface in low framerate scenarios.
Of course, this may just be a limitation, and as such, I request if the new Lua draw API comes to the HUD addresses this if it does not.

**Comment by NQ-Deckard** [comment]
I believe this may be a limitation, which may or may not be overcome if we add the Lua draw API. I do suspect however that it likely won't be as there is an intermediate state in the rendering process before it is displayed. However this is also related to an issue we are having with the current Lua screens and one of the reasons why an update has not made it to the PTS yet.

**Comment by EasternGamer** [comment]
> I believe this may be a limitation, which may or may not be overcome if we add the Lua draw API. I do suspect however that it likely won't be as there is an intermediate state in the rendering process before it is displayed. However this is also related to an issue we are having with the current Lua screens and one of the reasons why an update has not made it to the PTS yet.
