### ISSUE TITLE
impossible to get recipe from Transfer Unit

### ISSUE THREAD

**Issue by Jericho1060** [Archaegeo/DualUniverseLuaIssues#9]
Probably as it is not really using a schematic, the method `getCurrentSchematic()` is not returning the recipe chosen on a transfer unit

**Comment by NQ-Deckard** [comment]
This is quite likely true, I'll make a note of it.

**Comment by Archaegeo** [comment]
Test Close

**Comment by Jericho1060** [comment]
not solved, even on the PTS
